import { chromium } from '@playwright/test';
import { spawn } from 'node:child_process';
const server = spawn('npx', ['vite', 'preview', '--port', '4181', '--strictPort'], { shell: true, stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:4181/');
await page.waitForSelector('#game canvas');
await page.waitForTimeout(1500);
await page.keyboard.press('Enter');
await page.waitForSelector('.hud', { timeout: 10000 });
await page.evaluate(() => window.__aequitas.session.bus.emit('world:patrol', { name: 'patrulla-este', rank: 'alguacil', articulo: 'cp-28', map: 'plaza' }));
await page.waitForSelector('.intp', { timeout: 5000 });
await page.screenshot({ path: 'test-results/intp-1.png' });
await page.click('.intp__opt:has-text("Art. 28")');
await page.waitForTimeout(300);
const ok = await page.textContent('.intp__resultado');
await page.click('.intp__resultado button');
await page.waitForTimeout(500);
// Segunda: fallar → detención
await page.evaluate(() => window.__aequitas.session.bus.emit('world:patrol', { name: 'patrulla-este', rank: 'alguacil', articulo: 'cp-34', map: 'plaza' }));
await page.waitForSelector('.intp', { timeout: 5000 });
await page.click('.intp__opt:has-text("Art. 1 ")');
await page.waitForTimeout(300);
await page.click('.intp__resultado button');
await page.waitForTimeout(1200);
const st = await page.evaluate(() => { const s = window.__aequitas.session.state; return { ev: s.evidence, map: s.map, spawn: s.spawn, used: Object.keys(s.codiceUsedIn) }; });
console.log(JSON.stringify({ ok: ok?.slice(0, 60), st, toast: await page.locator('.ui-toast').textContent().catch(() => null), errors }));
await browser.close(); server.kill(); process.exit(0);
